[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true
name = "FAQ & Policy Assistant"
description = "AI-powered FAQ and policy management system"

# CRITICAL: Disable data persistence to prevent database conflicts
# DO NOT enable PostgreSQL connection as it conflicts with our custom database setup
# [data]
# provider = "postgres"
# connection_string = "postgresql://postgres:passwordnew@localhost:5432/postgres"

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 86400  # 24 hours (matching JWT expiry)

# Enable third parties caching (e.g., LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[features]
# Process and display HTML in messages. This can be a security risk
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Autoscroll new user messages at the top of the window
user_message_autoscroll = true

# DISABLE: Automatically tag threads (causes database conflicts)
auto_tag_thread = false

# Allow users to edit their own messages
edit_message = false

# Disable prompt playground to avoid conflicts
prompt_playground = false

# Multi-modal support
multi_modal = true

# Speech to text
speech_to_text = false

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = false  # Disabled to prevent conflicts
    accept = ["application/pdf", "text/plain", "image/*"]
    max_files = 5
    max_size_mb = 10

[features.audio]
    # Sample rate of the audio
    sample_rate = 24000

[features.mcp.sse]
    enabled = false  # Disabled to prevent conflicts

[features.mcp.stdio]
    enabled = false  # Disabled to prevent conflicts
    allowed_executables = []

[UI]
# Name of the assistant.
name = "FAQ Assistant"
default_language = "en-US"

# Default theme
default_theme = "light"

# Layout configuration
layout = "wide"

# Default sidebar state
default_sidebar_state = "closed"

# Description of the assistant. This is used for HTML tags.
description = "FAQ and Policy Assistant powered by static embeddings"

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "hidden"

# Show readme while thread is empty
show_readme_as_default = false

# Default collapse content for cleaner UI
default_collapse_content = true

# Default expand messages setting
default_expand_messages = false

# Hide chain of thought details
hide_cot = true

# Specify a CSS file that can be used to customize the user interface.
# custom_css = "/public/style.css"

# Specify a JavaScript file that can be used to customize the user interface.
# custom_js = "/public/script.js"

# Custom header links for navigation
[[UI.header_links]]
    name = "Admin"
    display_name = "Admin Panel"
    icon_url = "⚙️"
    url = "http://localhost:5000"

[[UI.header_links]]
    name = "Upload"
    display_name = "Document Upload"
    icon_url = "📄"
    url = "http://localhost:8001"

# Theme customization
[UI.theme]
    primary_color = "#667eea"
    background_color = "#ffffff"
    paper_color = "#ffffff"

    [UI.theme.dark]
        background_color = "#1a1a1a"
        paper_color = "#2d2d2d"

# CRITICAL: Disable data persistence completely
[data_persistence]
enabled = false

[meta]
generated_by = "2.5.5"

[copilot]
enabled = true
title = "FAQ Assistant"
description = "Ask me anything about company FAQs and policies. Powered by ultra-fast static embeddings (100x-400x faster on CPU)."
avatar = "🤖"
theme = "light"

[copilot.features]
enable_feedback = true
enable_download = false
enable_search = true

[copilot.ui]
primary_color = "#667eea"
background_color = "#ffffff"
border_radius = "12px"
font_family = "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"

# Authentication settings (compatible with our custom auth)
[auth]
# Use custom authentication (password callback)
enable = true
# Disable built-in OAuth to use our custom system
oauth_providers = []

# Session management
[session]
# Use in-memory sessions to avoid database conflicts
storage = "memory"
timeout = 86400  # 24 hours